apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-express-hpa
spec:
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
