apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-python/deployment.yaml
  - api-python/service.yaml
  - api-express/deployment.yaml
  - api-express/service.yaml
  - api-nest/deployment.yaml
  - api-nest/service.yaml
  - web/deployment.yaml
  - web/service.yaml
  - api-ingress.yaml
  - web-ingress.yaml
  - api-express/hpa.yaml
  - api-express/pdb.yaml
  - cluster-autoscaler.yaml
